### ISSUE TITLE
feat: create output for version

### ISSUE THREAD

**Issue by jef** [GoogleCloudPlatform/release-please-action#41]
### Description

It would be really handy if the action created a few outputs that would be useful for later steps like:

- `tag`: `1.0.0`
- `commit`: `62a67966c87f04fba1944c0fe548b018864bad71`

**Comment by bcoe** [comment]
@jef this seems like it would be a pretty reasonable addition. I think we'd need to make `release-please` return an object with this information when run programmatically perhaps?

**Comment by jef** [comment]
That's a good question. If `release-please` uses `@actions/core`, this could make this pretty straight forward (hopefully)!

https://github.com/actions/toolkit/tree/master/packages/core#inputsoutputs

**Comment by jef** [comment]
Or how ever this action interacts with `release-please` to be able to return that information. Then run `core.setOutput` on that value since `release-please` is outside of this action's scope.
