### ISSUE TITLE
Open PR with different account

### ISSUE THREAD

**Issue by ocervell** [GoogleCloudPlatform/release-please-action#73]
Is there a way to open a PR with a different GitHub user than the one GitHub chooses ? 
For google/ repos we need the committer to sign the CLA, can I assign a *-bot@google.com bot github account ?

**Comment by bcoe** [comment]
@ocervell yes 👍 we're actually doing this for `release-please-action` itself:

https://github.com/GoogleCloudPlatform/release-please-action/blob/main/.github/workflows/release-please.yaml#L12

I see you found the GitHub Application though, that can also be a great approach.
