### ISSUE TITLE
Action not creating release PR

### ISSUE THREAD

**Issue by lance** [GoogleCloudPlatform/release-please-action#74]
Hi - I am trying to use this action for a project, and for some reason it has not created a release PR. I have had [2 commits](https://github.com/boson-project/faas-js-runtime/compare/v0.2.3...master) since the last release, one of which adds `release-please-action`, and the other is a `feat: ...` commit. 

I see this message in the action logs.

> Run GoogleCloudPlatform/release-please-action@v2.2.0
> ✖ no recent release PRs found
> ✔ found 2 commits since 4ca4e99761601dc6a2300598a1952afc65c80f48
> ✔ release as minor: There are 0 BREAKING CHANGES and 1 features
> ✖ no user facing commits found since 4ca4e99761601dc6a2300598a1952afc65c80f48

Poking around the source code for `release-please`, I found this: https://github.com/googleapis/release-please/blob/6be995b2d05374eb5eea59a9b74219d2632fe830/src/releasers/node.ts#L56-L67 which checks to see if the commit message has more than one line here https://github.com/googleapis/release-please/blob/6be995b2d05374eb5eea59a9b74219d2632fe830/src/release-pr.ts#L303. 

The `feat: ...` commit message on my repo has two lines, so it's unclear to me why the action is bailing out here and not creating a PR.

**Comment by lance** [comment]
Update: Now three commits since the last release, the third is a `fix: ...` commit with a multi-line commit message. Still, no PR is created.

**Comment by bcoe** [comment]
@lance please try version `2.4.0` (I believe the `2.2.0` release had a bug in it).

Curious where did you find documentation that suggested `2.2.0`, I should make sure that's updated everywhere.
