### ISSUE TITLE
Call @actions/core setOutput with created tag

### ISSUE THREAD

**Issue by JasonEtco** [GoogleCloudPlatform/release-please-action#8]
👋 @bcoe! Following up on [this Twitter conversation](https://twitter.com/BenjaminCoe/status/1261371800451080192). It'd be rad if this action called `@actions/core`'s `setOutput` method, to use the tag that was created in the next actions in a workflow. I'm not sure where that's exposed, but if you can point me to it, happy to open a PR. It'd look something like this:

```js
const release = ReleasePRFactory.build(...)
await release.run()

// Assuming it's exposed on `ReleasePRFactory.tag_name`:
core.setOutput('tag_name', release.tag_name)
```

This would pair nicely with [build-and-tag-action](https://github.com/JasonEtco/build-and-tag-action)'s `tag_name` input!

**Comment by bcoe** [comment]
@JasonEtco I don't think it does so yet, but we could make this line:

```
https://github.com/bcoe/release-please-action/blob/master/index.js#L20
```

Return the tag of a release, if one is created?

**Comment by JasonEtco** [comment]
Nice, thanks for that @bcoe. I think this would also require an upstream change to `googleapis/release-please`, specifically here:

https://github.com/googleapis/release-please/blob/42e5bc6b8654afd4ce41e4c81333e1cf3bce75a5/src/github-release.ts#L81-L86

`GitHubRelease#createRelease` doesn't return or otherwise expose the generated release, or the tag (ex: we could get it from the release PR [over here](https://github.com/googleapis/release-please/blob/42e5bc6b8654afd4ce41e4c81333e1cf3bce75a5/src/github-release.ts#L58-L60)). I can open those two PRs (one there, one here) if you'd like! They'd be pretty simple:

```diff
class GitHubRelease {
  async createRelease() {
    // ...
-      await this.gh.createRelease(
+      const release = await this.gh.createRelease(
        this.packageName,
        gitHubReleasePR.version,
        gitHubReleasePR.sha,
        latestReleaseNotes
      );
   // ...
+  return release
}
```

```diff
- await gr.createRelease()
+ const release = await gr.createRelease()
+ core.setOutput('tag_name', release.tag_name)
```

**Comment by bcoe** [comment]
@JasonEtco bumped into a couple issues and had to rollback:

1. unfortunately need all the contents of the `dist/` folder.
2. release please currently looks at the sha of the last tag released to determine what commits have landed since the last release, since `build-and-tag-actions` forces a new `sha` this causes issues with the algorithm (I'm looking at changing this behavior to instead use the sha of the release that was last merged).
